import type { Metadata } from "next";
import "./globals.css";
// import Nav from "./_components/Nav";

export const metadata: Metadata = {
  title: "Voiled",
  description: "Generated by create next app",
};

function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        {/* <Nav/> */}
        {children}
      </body>
    </html>
  );
}

export default RootLayout